apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: logging
data:
  elasticsearch.yaml: |
    cluster.name: OliveSafety
    network.host: 0.0.0.0
    discovery.seed_hosts: ["elasticsearch-discovery"]
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.http.ssl.client_authentication: required
    xpack.security.transport.ssl.keystore.path: certs/kibana.p12
    xpack.security.transport.ssl.truststore.path: certs/kibana.p12