apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type forward
      <security>
        self_hostname flb.local
        shared_key secret
      </security>
    </source>
    
    <match **>
      @type elasticsearch
      host elasticsearch.logging
      port 9200
      logstash_format true
      include_timestamp true
      user      olive
      password  olivesafety!
      ssl_verify false
    </match>