apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
    </source>
  
    <label @FLUENT_LOG>
      <match **>
        @type elasticsearch
        host elasticsearch.logging
        port 9200
        ssl_verify_mode full
        ssl_ca_path /fluentd/etc/certs/ca.crt
        ssl_cert_path /fluentd/etc/certs/kibana.crt
        ssl_key_path /fluentd/etc/certs/kibana.key
        logstash_format false
        include_timestamp true
        tag_key @log_name
      </match>
    </label>
