apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:8.15.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5601
            protocol: TCP
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch.logging.svc.cluster.local:9200
            - name: discovery.type
              value: single-node
            # - name: ELASTICSEARCH_USERNAME
            #   value: "elastic"
            # - name: ELASTICSEARCH_PASSWORD
            #   value: "elastic-search"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana-svc
  namespace: logging
spec:
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
    nodePort: 30561
  type: NodePort
