apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.17.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5601
            protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/kibana/config/kibana.yml
              name: config
              subPath: kibana.yml
#            - name: kibana-ssl
#              mountPath: /etc/kibana/ssl
#              readOnly: true
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch.logging:9200
            - name: discovery.type
              value: single-node
            - name: ELASTICSEARCH_USERNAME
              value: "elastic"
            - name: ELASTICSEARCH_PASSWORD
              value: "elastic-search"
            - name: SERVER_NAME
              value: http://kibana.joon-test.shop
      volumes:
        - name: config
          configMap:
            name: kibana-config
#        - name: kibana-ssl
#          secret:
#            secretName: kibana-ssl-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana
  namespace: logging
spec:
  selector:
    app: kibana
  ports:
  - nodePort: 30651
    port: 5601
    protocol: TCP
    targetPort: 5601
  type: NodePort

---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: kibana-ingress
#  namespace: logging
#  annotations:
#    alb.ingress.kubernetes.io/scheme: internet-facing
#    alb.ingress.kubernetes.io/target-type: ip
#  labels:
#    name: kibana-ingress
#spec:
#  ingressClassName: "alb-ingress-class"
#  rules:
#    - host: kibana.joon-test.shop
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: kibana
#                port:
#                  number: 5601
