apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs-pvc
  namespace: logging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: certs-pv
  namespace: logging
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/certs
  claimRef:
    name: certs-pvc
    namespace: logging