apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: logging
  labels:
    app: kibana
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    elasticsearch.hosts: [ "http://elasticsearch.logging:9200" ]
    server.publicBaseUrl: ${{ secrets.SERVER_NAME }}
    elasticsearch.username: "${ ELASTICSEARCH_USERNAME }"
    elasticsearch.password: "${ ELASTICSEARCH_PASSWORD }"
    xpack.encryptedSavedObjects.encryptionKey: ${{ vars.ENCRYPTEDSAVEDOBJECTS }}
    xpack.reporting.encryptionKey: ${{ vars.REPORTING }}
    xpack.security.encryptionKey: ${{ vars.SECURITY }}
    xpack.security.enabled: true