apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.10.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5601
              protocol: TCP
#          command:
#            - "sh"
#            - "-c"
#            - "bin/kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-alerting/opendistroAlertingKibana-1.13.0.0.zip"
          volumeMounts:
            - mountPath: /usr/share/kibana/config/kibana.yml
              name: config
              subPath: kibana.yml
          #            - name: ssl
          #              mountPath: /usr/share/kibana/config/certs
          #              readOnly: true
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch.logging:9200
            - name: discovery.type
              value: single-node
            - name: ELASTICSEARCH_USERNAME
              value: "olive"
            - name: ELASTICSEARCH_PASSWORD
              value: "olivesafety!"
            - name: SERVER_NAME
              value: http://kibana.joon-test.shop
      volumes:
        - name: config
          configMap:
            name: kibana-config
#        - name: ssl
#          secret:
#            secretName: kibana-ssl

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
    - nodePort: 30651
      port: 5601
      protocol: TCP
      targetPort: 5601
  type: NodePort
